In [5]:
import tensorflow as tf
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "rnn"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "img", CHAPTER_ID, fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

## Manual RNN

In [6]:
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None,n_inputs])
X1 = tf.placeholder(tf.float32, [None,n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs,n_neurons],dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))
b = tf.Variable(tf.zeros([1,n_neurons],dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0,Wx)+b)
Y1 = tf.tanh(tf.matmul(Y0,Wy)+ tf.matmul(X1,Wx)+b)

init = tf.global_variables_initializer()


In [7]:
import numpy as np

#Mini-Batch: instance 0, instance 1, instance 2,instance 3,
X0_batch = np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]]) # t = 0
X1_batch = np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]]) # t = 1

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0,Y1],feed_dict={X0: X0_batch, X1: X1_batch})

In [8]:
print(Y0_val) # output at t = 0

[[ 0.9797263  -0.8717233   0.36186677 -0.999255    0.9520225 ]
 [ 0.99996483 -0.9999434   0.999671   -1.          0.9984565 ]
 [ 0.99999994 -1.          0.9999999  -1.          0.9999515 ]
 [-0.775507   -0.9957266   1.         -1.          0.86053956]]


In [9]:
print(Y1_val) # output at t = 1 

[[ 1.         -1.          1.         -1.          0.89766204]
 [ 0.9897112   0.14877084 -0.89885545 -0.6353301  -0.98374885]
 [ 0.999997   -0.99999326  0.99999017 -1.         -0.6619058 ]
 [ 0.90627015 -0.9686446   0.75485164 -0.9999993  -0.995037  ]]
